name: mindmate_patient
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  audioplayers: ^6.5.1
  flutter:
    sdk: flutter
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  record: ^6.1.2
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
